-- MySQL Script generated by MySQL Workbench
-- 07/16/16 18:12:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema koaladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema koaladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koaladb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `koaladb` ;

-- -----------------------------------------------------
-- Table `koaladb`.`TIPO_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`TIPO_USUARIO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`TIPO_USUARIO` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_tipo_usuario` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_usuario`)  COMMENT '',
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_tipo_usuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_usuario` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  `celular` INT NOT NULL COMMENT '',
  `atualiza_celular` TINYINT(1) NULL COMMENT '',
  `atualiza_email` TINYINT(1) NULL COMMENT '',
  `TIPO_USUARIO_id_tipo_usuario` INT NOT NULL COMMENT '',
  `foto` LONGBLOB NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  UNIQUE INDEX `idUsuario_UNIQUE` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_Usuario_TIPO_USUARIO_idx` (`TIPO_USUARIO_id_tipo_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_TIPO_USUARIO`
    FOREIGN KEY (`TIPO_USUARIO_id_tipo_usuario`)
    REFERENCES `koaladb`.`TIPO_USUARIO` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`MOEDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`MOEDA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`MOEDA` (
  `id_moeda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_moeda` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_moeda`)  COMMENT '',
  UNIQUE INDEX `id_moeda_UNIQUE` (`id_moeda` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`CONTINENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`CONTINENTE` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`CONTINENTE` (
  `id_continente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_continente` VARCHAR(75) NOT NULL COMMENT '',
  PRIMARY KEY (`id_continente`)  COMMENT '',
  UNIQUE INDEX `id_continente_UNIQUE` (`id_continente` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`PAIS` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`PAIS` (
  `id_pais` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_pais` VARCHAR(45) NOT NULL COMMENT '',
  `MOEDA_id_moeda` INT NOT NULL COMMENT '',
  `CONTINENTE_id_continente` INT NOT NULL COMMENT '',
  `capital` VARCHAR(65) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pais`)  COMMENT '',
  UNIQUE INDEX `id_pais_UNIQUE` (`id_pais` ASC)  COMMENT '',
  INDEX `fk_PAIS_MOEDA1_idx` (`MOEDA_id_moeda` ASC)  COMMENT '',
  INDEX `fk_PAIS_CONTINENTE1_idx` (`CONTINENTE_id_continente` ASC)  COMMENT '',
  CONSTRAINT `fk_PAIS_MOEDA1`
    FOREIGN KEY (`MOEDA_id_moeda`)
    REFERENCES `koaladb`.`MOEDA` (`id_moeda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAIS_CONTINENTE1`
    FOREIGN KEY (`CONTINENTE_id_continente`)
    REFERENCES `koaladb`.`CONTINENTE` (`id_continente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ESTADO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ESTADO` (
  `id_estado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_estado` VARCHAR(75) NOT NULL COMMENT '',
  `capital` VARCHAR(65) NOT NULL COMMENT '',
  `PAIS_id_pais` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_estado`)  COMMENT '',
  UNIQUE INDEX `id_estados_UNIQUE` (`id_estado` ASC)  COMMENT '',
  INDEX `fk_ESTADO_PAIS1_idx` (`PAIS_id_pais` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTADO_PAIS1`
    FOREIGN KEY (`PAIS_id_pais`)
    REFERENCES `koaladb`.`PAIS` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`CIDADE` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`CIDADE` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_cidade` VARCHAR(65) NOT NULL COMMENT '',
  `ESTADO_id_estado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_cidade`)  COMMENT '',
  UNIQUE INDEX `id_cidades_UNIQUE` (`id_cidade` ASC)  COMMENT '',
  INDEX `fk_CIDADE_ESTADO1_idx` (`ESTADO_id_estado` ASC)  COMMENT '',
  CONSTRAINT `fk_CIDADE_ESTADO1`
    FOREIGN KEY (`ESTADO_id_estado`)
    REFERENCES `koaladb`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ESTABELECIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ESTABELECIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ESTABELECIMENTO` (
  `id_estabelecimento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_estabelecimento` VARCHAR(45) NOT NULL COMMENT '',
  `cep` VARCHAR(45) NOT NULL COMMENT '',
  `about` VARCHAR(500) NOT NULL COMMENT '',
  `telefone` INT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `classificacao` DECIMAL(1,1) NULL COMMENT '',
  `foto` LONGBLOB NULL COMMENT '',
  `CIDADE_id_cidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_estabelecimento`)  COMMENT '',
  UNIQUE INDEX `id_estabelecimento_UNIQUE` (`id_estabelecimento` ASC)  COMMENT '',
  INDEX `fk_ESTABELECIMENTO_CIDADE1_idx` (`CIDADE_id_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTABELECIMENTO_CIDADE1`
    FOREIGN KEY (`CIDADE_id_cidade`)
    REFERENCES `koaladb`.`CIDADE` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`TIPO_ESTABELECIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`TIPO_ESTABELECIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`TIPO_ESTABELECIMENTO` (
  `id_tipo_estabelecimento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_tipo_estabelecimento` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_estabelecimento`)  COMMENT '',
  UNIQUE INDEX `id_tipo_estabelecimento_UNIQUE` (`id_tipo_estabelecimento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO` (
  `ESTABELECIMENTO_id_estabelecimento` INT NOT NULL COMMENT '',
  `TIPO_ESTABELECIMENTO_id_tipo_estabelecimento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ESTABELECIMENTO_id_estabelecimento`, `TIPO_ESTABELECIMENTO_id_tipo_estabelecimento`)  COMMENT '',
  INDEX `fk_ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO_TIPO_ESTABELECI_idx` (`TIPO_ESTABELECIMENTO_id_tipo_estabelecimento` ASC)  COMMENT '',
  INDEX `fk_ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO_ESTABELECIMENTO_idx` (`ESTABELECIMENTO_id_estabelecimento` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO_ESTABELECIMENTO1`
    FOREIGN KEY (`ESTABELECIMENTO_id_estabelecimento`)
    REFERENCES `koaladb`.`ESTABELECIMENTO` (`id_estabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTABELECIMENTO_has_TIPO_ESTABELECIMENTO_TIPO_ESTABELECIME1`
    FOREIGN KEY (`TIPO_ESTABELECIMENTO_id_tipo_estabelecimento`)
    REFERENCES `koaladb`.`TIPO_ESTABELECIMENTO` (`id_tipo_estabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`DIA_SEMANA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`DIA_SEMANA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`DIA_SEMANA` (
  `id_dia_semana` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_dia_semana` VARCHAR(45) NOT NULL COMMENT '',
  `horario_inicio` TIME NOT NULL COMMENT '',
  `horario_fim` TIME NOT NULL COMMENT '',
  PRIMARY KEY (`id_dia_semana`)  COMMENT '',
  UNIQUE INDEX `id_dias_semana_UNIQUE` (`id_dia_semana` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ESTABELECIMENTO_has_DIA_SEMANA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ESTABELECIMENTO_has_DIA_SEMANA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ESTABELECIMENTO_has_DIA_SEMANA` (
  `ESTABELECIMENTO_id_estabelecimento` INT NOT NULL COMMENT '',
  `DIAS_SEMANA_id_dia_semana` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ESTABELECIMENTO_id_estabelecimento`, `DIAS_SEMANA_id_dia_semana`)  COMMENT '',
  INDEX `fk_ESTABELECIMENTO_has_DIAS_SEMANA_DIAS_SEMANA1_idx` (`DIAS_SEMANA_id_dia_semana` ASC)  COMMENT '',
  INDEX `fk_ESTABELECIMENTO_has_DIAS_SEMANA_ESTABELECIMENTO1_idx` (`ESTABELECIMENTO_id_estabelecimento` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTABELECIMENTO_has_DIAS_SEMANA_ESTABELECIMENTO1`
    FOREIGN KEY (`ESTABELECIMENTO_id_estabelecimento`)
    REFERENCES `koaladb`.`ESTABELECIMENTO` (`id_estabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTABELECIMENTO_has_DIAS_SEMANA_DIAS_SEMANA1`
    FOREIGN KEY (`DIAS_SEMANA_id_dia_semana`)
    REFERENCES `koaladb`.`DIA_SEMANA` (`id_dia_semana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`IDIOMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`IDIOMA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`IDIOMA` (
  `id_idioma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_idioma` VARCHAR(75) NOT NULL COMMENT '',
  PRIMARY KEY (`id_idioma`)  COMMENT '',
  UNIQUE INDEX `id_linguas_UNIQUE` (`id_idioma` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`PAIS_has_IDIOMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`PAIS_has_IDIOMA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`PAIS_has_IDIOMA` (
  `PAIS_id_pais` INT NOT NULL COMMENT '',
  `IDIOMA_id_idioma` INT NOT NULL COMMENT '',
  PRIMARY KEY (`PAIS_id_pais`, `IDIOMA_id_idioma`)  COMMENT '',
  INDEX `fk_PAIS_has_IDIOMA_IDIOMA1_idx` (`IDIOMA_id_idioma` ASC)  COMMENT '',
  INDEX `fk_PAIS_has_IDIOMA_PAIS1_idx` (`PAIS_id_pais` ASC)  COMMENT '',
  CONSTRAINT `fk_PAIS_has_IDIOMA_PAIS1`
    FOREIGN KEY (`PAIS_id_pais`)
    REFERENCES `koaladb`.`PAIS` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAIS_has_IDIOMA_IDIOMA1`
    FOREIGN KEY (`IDIOMA_id_idioma`)
    REFERENCES `koaladb`.`IDIOMA` (`id_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ENTRETENIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ENTRETENIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ENTRETENIMENTO` (
  `id_entretenimento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_entretenimento` VARCHAR(45) NOT NULL COMMENT '',
  `vl_entrada` DECIMAL(15,2) NULL COMMENT '',
  `vl_meia_entrada` DECIMAL(15,2) NULL COMMENT '',
  `about` VARCHAR(500) NOT NULL COMMENT '',
  `cep` DECIMAL(10,0) NOT NULL COMMENT '',
  `telefone` DECIMAL(10,0) NULL COMMENT '',
  `foto` LONGBLOB NULL COMMENT '',
  `classificacao` DECIMAL(1,1) NULL COMMENT '',
  `site` VARCHAR(75) NULL COMMENT '',
  PRIMARY KEY (`id_entretenimento`)  COMMENT '',
  UNIQUE INDEX `id_entretenimento_UNIQUE` (`id_entretenimento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`EVENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`EVENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`EVENTO` (
  `id_evento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_evento` VARCHAR(75) NOT NULL COMMENT '',
  `dt_inicio` DATE NOT NULL COMMENT '',
  `dt_fim` DATE NOT NULL COMMENT '',
  `cep` DECIMAL(10,0) NOT NULL COMMENT '',
  `ds_local_evento` VARCHAR(75) NOT NULL COMMENT '',
  `horario_inicio` TIME NOT NULL COMMENT '',
  `horario_fim` TIME NOT NULL COMMENT '',
  `vl_entrada` DECIMAL(15,2) NULL COMMENT '',
  `vl_meia_entrada` DECIMAL(15,2) NULL COMMENT '',
  `site` VARCHAR(65) NULL COMMENT '',
  `about` VARCHAR(500) NOT NULL COMMENT '',
  `telefone` DECIMAL(15) NULL COMMENT '',
  `foto` LONGBLOB NULL COMMENT '',
  PRIMARY KEY (`id_evento`)  COMMENT '',
  UNIQUE INDEX `id_evento_UNIQUE` (`id_evento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`COMENTARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`COMENTARIO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`COMENTARIO` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_comentario` VARCHAR(500) NOT NULL COMMENT '',
  `ESTABELECIMENTO_id_estabelecimento` INT NULL COMMENT '',
  `ENTRETENIMENTO_id_entretenimento` INT NULL COMMENT '',
  `USUARIO_id_usuario` INT NOT NULL COMMENT '',
  `EVENTO_id_evento` INT NULL COMMENT '',
  PRIMARY KEY (`id_comentario`)  COMMENT '',
  UNIQUE INDEX `id_comentario_UNIQUE` (`id_comentario` ASC)  COMMENT '',
  INDEX `fk_COMENTARIO_ESTABELECIMENTO1_idx` (`ESTABELECIMENTO_id_estabelecimento` ASC)  COMMENT '',
  INDEX `fk_COMENTARIO_ENTRETENIMENTO1_idx` (`ENTRETENIMENTO_id_entretenimento` ASC)  COMMENT '',
  INDEX `fk_COMENTARIO_USUARIO1_idx` (`USUARIO_id_usuario` ASC)  COMMENT '',
  INDEX `fk_COMENTARIO_EVENTO1_idx` (`EVENTO_id_evento` ASC)  COMMENT '',
  CONSTRAINT `fk_COMENTARIO_ESTABELECIMENTO1`
    FOREIGN KEY (`ESTABELECIMENTO_id_estabelecimento`)
    REFERENCES `koaladb`.`ESTABELECIMENTO` (`id_estabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_ENTRETENIMENTO1`
    FOREIGN KEY (`ENTRETENIMENTO_id_entretenimento`)
    REFERENCES `koaladb`.`ENTRETENIMENTO` (`id_entretenimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `koaladb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_EVENTO1`
    FOREIGN KEY (`EVENTO_id_evento`)
    REFERENCES `koaladb`.`EVENTO` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ENTRETENIMENTO_has_DIA_SEMANA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ENTRETENIMENTO_has_DIA_SEMANA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ENTRETENIMENTO_has_DIA_SEMANA` (
  `ENTRETENIMENTO_id_entretenimento` INT NOT NULL COMMENT '',
  `DIA_SEMANA_id_dia_semana` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ENTRETENIMENTO_id_entretenimento`, `DIA_SEMANA_id_dia_semana`)  COMMENT '',
  INDEX `fk_ENTRETENIMENTO_has_DIA_SEMANA_DIA_SEMANA1_idx` (`DIA_SEMANA_id_dia_semana` ASC)  COMMENT '',
  INDEX `fk_ENTRETENIMENTO_has_DIA_SEMANA_ENTRETENIMENTO1_idx` (`ENTRETENIMENTO_id_entretenimento` ASC)  COMMENT '',
  CONSTRAINT `fk_ENTRETENIMENTO_has_DIA_SEMANA_ENTRETENIMENTO1`
    FOREIGN KEY (`ENTRETENIMENTO_id_entretenimento`)
    REFERENCES `koaladb`.`ENTRETENIMENTO` (`id_entretenimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENTRETENIMENTO_has_DIA_SEMANA_DIA_SEMANA1`
    FOREIGN KEY (`DIA_SEMANA_id_dia_semana`)
    REFERENCES `koaladb`.`DIA_SEMANA` (`id_dia_semana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`TIPO_ENTRETENIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`TIPO_ENTRETENIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`TIPO_ENTRETENIMENTO` (
  `id_tipo_entretenimento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_tipo_entretenimento` VARCHAR(75) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_entretenimento`)  COMMENT '',
  UNIQUE INDEX `id_tipo_entretenimento_UNIQUE` (`id_tipo_entretenimento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO` (
  `ENTRETENIMENTO_id_entretenimento` INT NOT NULL COMMENT '',
  `TIPO_ENTRETENIMENTO_id_tipo_entretenimento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ENTRETENIMENTO_id_entretenimento`, `TIPO_ENTRETENIMENTO_id_tipo_entretenimento`)  COMMENT '',
  INDEX `fk_ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO_TIPO_ENTRETENIMEN_idx` (`TIPO_ENTRETENIMENTO_id_tipo_entretenimento` ASC)  COMMENT '',
  INDEX `fk_ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO_ENTRETENIMENTO1_idx` (`ENTRETENIMENTO_id_entretenimento` ASC)  COMMENT '',
  CONSTRAINT `fk_ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO_ENTRETENIMENTO1`
    FOREIGN KEY (`ENTRETENIMENTO_id_entretenimento`)
    REFERENCES `koaladb`.`ENTRETENIMENTO` (`id_entretenimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENTRETENIMENTO_has_TIPO_ENTRETENIMENTO_TIPO_ENTRETENIMENTO1`
    FOREIGN KEY (`TIPO_ENTRETENIMENTO_id_tipo_entretenimento`)
    REFERENCES `koaladb`.`TIPO_ENTRETENIMENTO` (`id_tipo_entretenimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`TIPO_EVENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`TIPO_EVENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`TIPO_EVENTO` (
  `id_tipo_evento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_tipo_evento` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_evento`)  COMMENT '',
  UNIQUE INDEX `id_tipo_evento_UNIQUE` (`id_tipo_evento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`EVENTO_has_TIPO_EVENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`EVENTO_has_TIPO_EVENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`EVENTO_has_TIPO_EVENTO` (
  `EVENTO_id_evento` INT NOT NULL COMMENT '',
  `TIPO_EVENTO_id_tipo_evento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`EVENTO_id_evento`, `TIPO_EVENTO_id_tipo_evento`)  COMMENT '',
  INDEX `fk_EVENTO_has_TIPO_EVENTO_TIPO_EVENTO1_idx` (`TIPO_EVENTO_id_tipo_evento` ASC)  COMMENT '',
  INDEX `fk_EVENTO_has_TIPO_EVENTO_EVENTO1_idx` (`EVENTO_id_evento` ASC)  COMMENT '',
  CONSTRAINT `fk_EVENTO_has_TIPO_EVENTO_EVENTO1`
    FOREIGN KEY (`EVENTO_id_evento`)
    REFERENCES `koaladb`.`EVENTO` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTO_has_TIPO_EVENTO_TIPO_EVENTO1`
    FOREIGN KEY (`TIPO_EVENTO_id_tipo_evento`)
    REFERENCES `koaladb`.`TIPO_EVENTO` (`id_tipo_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ROTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ROTA` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ROTA` (
  `id_rota` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_rota` VARCHAR(45) NOT NULL COMMENT '',
  `dt_inicio` DATE NOT NULL COMMENT '',
  `dt_fim` DATE NOT NULL COMMENT '',
  `USUARIO_id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_rota`)  COMMENT '',
  UNIQUE INDEX `id_rota_UNIQUE` (`id_rota` ASC)  COMMENT '',
  INDEX `fk_ROTA_USUARIO1_idx` (`USUARIO_id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_ROTA_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `koaladb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ROTA_has_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ROTA_has_ESTADO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ROTA_has_ESTADO` (
  `ROTA_id_rota` INT NOT NULL COMMENT '',
  `ESTADO_id_estado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ROTA_id_rota`, `ESTADO_id_estado`)  COMMENT '',
  INDEX `fk_ROTA_has_ESTADO_ESTADO1_idx` (`ESTADO_id_estado` ASC)  COMMENT '',
  INDEX `fk_ROTA_has_ESTADO_ROTA1_idx` (`ROTA_id_rota` ASC)  COMMENT '',
  CONSTRAINT `fk_ROTA_has_ESTADO_ROTA1`
    FOREIGN KEY (`ROTA_id_rota`)
    REFERENCES `koaladb`.`ROTA` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROTA_has_ESTADO_ESTADO1`
    FOREIGN KEY (`ESTADO_id_estado`)
    REFERENCES `koaladb`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ROTA_has_CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ROTA_has_CIDADE` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ROTA_has_CIDADE` (
  `ROTA_id_rota` INT NOT NULL COMMENT '',
  `CIDADE_id_cidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ROTA_id_rota`, `CIDADE_id_cidade`)  COMMENT '',
  INDEX `fk_ROTA_has_CIDADE_CIDADE1_idx` (`CIDADE_id_cidade` ASC)  COMMENT '',
  INDEX `fk_ROTA_has_CIDADE_ROTA1_idx` (`ROTA_id_rota` ASC)  COMMENT '',
  CONSTRAINT `fk_ROTA_has_CIDADE_ROTA1`
    FOREIGN KEY (`ROTA_id_rota`)
    REFERENCES `koaladb`.`ROTA` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROTA_has_CIDADE_CIDADE1`
    FOREIGN KEY (`CIDADE_id_cidade`)
    REFERENCES `koaladb`.`CIDADE` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ROTA_has_ESTABELECIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ROTA_has_ESTABELECIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ROTA_has_ESTABELECIMENTO` (
  `ROTA_id_rota` INT NOT NULL COMMENT '',
  `ESTABELECIMENTO_id_estabelecimento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ROTA_id_rota`, `ESTABELECIMENTO_id_estabelecimento`)  COMMENT '',
  INDEX `fk_ROTA_has_ESTABELECIMENTO_ESTABELECIMENTO1_idx` (`ESTABELECIMENTO_id_estabelecimento` ASC)  COMMENT '',
  INDEX `fk_ROTA_has_ESTABELECIMENTO_ROTA1_idx` (`ROTA_id_rota` ASC)  COMMENT '',
  CONSTRAINT `fk_ROTA_has_ESTABELECIMENTO_ROTA1`
    FOREIGN KEY (`ROTA_id_rota`)
    REFERENCES `koaladb`.`ROTA` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROTA_has_ESTABELECIMENTO_ESTABELECIMENTO1`
    FOREIGN KEY (`ESTABELECIMENTO_id_estabelecimento`)
    REFERENCES `koaladb`.`ESTABELECIMENTO` (`id_estabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ROTA_has_ENTRETENIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ROTA_has_ENTRETENIMENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ROTA_has_ENTRETENIMENTO` (
  `ROTA_id_rota` INT NULL COMMENT '',
  `ENTRETENIMENTO_id_entretenimento` INT NULL COMMENT '',
  PRIMARY KEY (`ROTA_id_rota`, `ENTRETENIMENTO_id_entretenimento`)  COMMENT '',
  INDEX `fk_ROTA_has_ENTRETENIMENTO_ENTRETENIMENTO1_idx` (`ENTRETENIMENTO_id_entretenimento` ASC)  COMMENT '',
  INDEX `fk_ROTA_has_ENTRETENIMENTO_ROTA1_idx` (`ROTA_id_rota` ASC)  COMMENT '',
  CONSTRAINT `fk_ROTA_has_ENTRETENIMENTO_ROTA1`
    FOREIGN KEY (`ROTA_id_rota`)
    REFERENCES `koaladb`.`ROTA` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROTA_has_ENTRETENIMENTO_ENTRETENIMENTO1`
    FOREIGN KEY (`ENTRETENIMENTO_id_entretenimento`)
    REFERENCES `koaladb`.`ENTRETENIMENTO` (`id_entretenimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koaladb`.`ROTA_has_EVENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koaladb`.`ROTA_has_EVENTO` ;

CREATE TABLE IF NOT EXISTS `koaladb`.`ROTA_has_EVENTO` (
  `ROTA_id_rota` INT NOT NULL COMMENT '',
  `EVENTO_id_evento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ROTA_id_rota`, `EVENTO_id_evento`)  COMMENT '',
  INDEX `fk_ROTA_has_EVENTO_EVENTO1_idx` (`EVENTO_id_evento` ASC)  COMMENT '',
  INDEX `fk_ROTA_has_EVENTO_ROTA1_idx` (`ROTA_id_rota` ASC)  COMMENT '',
  CONSTRAINT `fk_ROTA_has_EVENTO_ROTA1`
    FOREIGN KEY (`ROTA_id_rota`)
    REFERENCES `koaladb`.`ROTA` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROTA_has_EVENTO_EVENTO1`
    FOREIGN KEY (`EVENTO_id_evento`)
    REFERENCES `koaladb`.`EVENTO` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
